### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by gybeny** [DevEvil99/Discord-Ticket-Bot#1]
C:\Users\GYBeny\Desktop\huh\Discord-Ticket-Bot\index.js:6
const { red, green, blue } = require("chalk");
                             ^

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\GYBeny\Desktop\huh\Discord-Ticket-Bot\node_modules\chalk\source\index.js from C:\Users\GYBeny\Desktop\huh\Discord-Ticket-Bot\index.js not supported.
Instead change the require of C:\Users\GYBeny\Desktop\huh\Discord-Ticket-Bot\node_modules\chalk\source\index.js in C:\Users\GYBeny\Desktop\huh\Discord-Ticket-Bot\index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (C:\Users\GYBeny\Desktop\huh\Discord-Ticket-Bot\index.js:6:30) {
  code: ←[32m'ERR_REQUIRE_ESM'←[39m
}

C:\Users\GYBeny\Desktop\huh\Discord-Ticket-Bot>

**Comment by DevEvil99** [comment]
Remove chalk from code and node_modules

**Comment by gybeny** [comment]
Thanks
