### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by Yeager28** [DevEvil99/Discord-Ticket-Bot#3]
![Screenshot_1](https://user-images.githubusercontent.com/110985217/183915768-41b20d2a-ad0a-4403-b11f-482a369d7195.png)

**Comment by DevEvil99** [comment]
replace the index.js with the new code

**Comment by Yeager28** [comment]
```
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
customer@sparkedhost~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
NodeJS version: v18.1.0
customer@sparkedhost~ Server marked as running...
NPM version: 8.8.0
Yarn version: 22.18
Git version: 2.30.2
customer@sparkedhost:~# if [[ -d .git ]]; then git pull; fi; if [[ ! -z ${NODE_PACKAGES} ]]; then npm install ${NODE_PACKAGES}; fi; if [ -f /home/container/package.json ]; then npm install --production; fi; node /home/container/${STARTUP_FILE}
npm WARN deprecated discord.js@12.5.3: no longer supported
[##################] / reify:lodash: http fetch GET 200 https://registry.npmjs.
[##################] / reify:lodash: http fetch GET 200 https://registry.npmjs.
[##################] / reify:lodash: http fetch GET 200 https://registry.npmjs.
[##################] / reify:lodash: http fetch GET 200 https://registry.npmjs.
added 91 packages, and audited 92 packages in 2m
8 packages are looking for funding
  run `npm fund` for details
3 vulnerabilities (2 high, 1 critical)
To address all issues, run:
  npm audit fix
Run `npm audit` for details.
npm notice 
npm notice New minor version of npm available! 8.8.0 -> 8.17.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.17.0
npm notice Run npm install -g npm@8.17.0 to update!
npm notice 
npm WARN config production Use `--omit=dev` instead.

up to date, audited 92 packages in 1s
8 packages are looking for funding
  run `npm fund` for details
3 vulnerabilities (2 high, 1 critical)
To address all issues, run:
  npm audit fix
Run `npm audit` for details.
ReferenceError: join is not defined
    at Object.<anonymous> (./index.js:45:22)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```
it shows this now
you got discord?

**Comment by DevEvil99** [comment]
replace index.js with new code again

**Comment by Yeager28** [comment]
customer@sparkedhost~ Server marked as offline...
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
customer@sparkedhost~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
NodeJS version: v18.1.0
customer@sparkedhost~ Server marked as running...
NPM version: 8.8.0
Yarn version: 22.18
Git version: 2.30.2
customer@sparkedhost:~# if [[ -d .git ]]; then git pull; fi; if [[ ! -z ${NODE_PACKAGES} ]]; then npm install ${NODE_PACKAGES}; fi; if [ -f /home/container/package.json ]; then npm install --production; fi; node /home/container/${STARTUP_FILE}

up to date, audited 92 packages in 2s
8 packages are looking for funding
  run `npm fund` for details
3 vulnerabilities (2 high, 1 critical)
To address all issues, run:
  npm audit fix
Run `npm audit` for details.
npm WARN config production Use `--omit=dev` instead.

up to date, audited 92 packages in 1s
8 packages are looking for funding
  run `npm fund` for details
3 vulnerabilities (2 high, 1 critical)
To address all issues, run:
  npm audit fix
Run `npm audit` for details.
/home/container/index.js:9
const fs = require("fs");
      ^
SyntaxError: Identifier 'fs' has already been declared
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
Node.js v18.1.0
customer@sparkedhost~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
customer@sparkedhost~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
NodeJS version: v18.1.0
customer@sparkedhost~ Server marked as running...
NPM version: 8.8.0
Yarn version: 22.18
Git version: 2.30.2
customer@sparkedhost:~# if [[ -d .git ]]; then git pull; fi; if [[ ! -z ${NODE_PACKAGES} ]]; then npm install ${NODE_PACKAGES}; fi; if [ -f /home/container/package.json ]; then npm install --production; fi; node /home/container/${STARTUP_FILE}

up to date, audited 92 packages in 1s
8 packages are looking for funding
  run `npm fund` for details
3 vulnerabilities (2 high, 1 critical)
To address all issues, run:
  npm audit fix
Run `npm audit` for details.
npm WARN config production Use `--omit=dev` instead.

up to date, audited 92 packages in 1s
8 packages are looking for funding
  run `npm fund` for details
3 vulnerabilities (2 high, 1 critical)
To address all issues, run:
  npm audit fix
Run `npm audit` for details.
/home/container/index.js:9
const fs = require("fs");
      ^
SyntaxError: Identifier 'fs' has already been declared
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
Node.js v18.1.0
customer@sparkedhost~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

**Comment by DevEvil99** [comment]
Delete one of the fs lines, I accidentally typed it twice
